[[item]]
file = '~/.config/alacritty/alacritty.yml'
template = 'alacritty'
subtemplate = 'default'
rewrite = false
start = '# Start flavours'
end = '# End flavours'
hook = ''
light = true

[[item]]
file = '~/.config/zathura/zathurarc'
template = 'zathura'
subtemplate = 'default'
rewrite = false
start = '# Start flavours'
end = '# End flavours'
hook = ''
light = true

[[item]]
file = '~/.Xresources'
template = 'xresources'
subtemplate = 'default'
rewrite = false
start = '! Start flavours'
end = '! End flavours'
hook = ''
light = true

[[item]]
file = '~/.config/nvim/plugins/base16-vim/colors/base16-3024.vim'
template = 'vim'
subtemplate = 'default'
rewrite = false
start = '" Start flavours'
end = '" End flavours'
hook = ''
light = true

[[item]]
file = '~/.config/rofi/config.rasi'
template = 'rofi'
subtemplate = 'default'
rewrite = false
start = '/* Start flavours */'
end = '/* End flavours */'
hook = ''
light = true

[[item]]
file = '~/.config/dunst/dunstrc'
template = 'dunst'
subtemplate = 'default'
rewrite = false
start = '# Start flavours'
end = '# End flavours'
hook = ''
light = true

[[item]]
file = '~/.config/bspwm/bspwmlooks'
template = 'bspwm'
subtemplate = 'default'
rewrite = false
start = '# Start flavours'
end = '# End flavours'
hook = ''
light = true

[[item]]
file = '/home/tarsiec/.local/pkg/dmenu/config.h'
template = 'dmenu'
subtemplate = 'default'
rewrite = false
start = '/* Start flavours */'
end = '/* End flavours */'
hook = ''
light = true

[[item]]
file = '/home/tarsiec/.local/pkg/tabbed/config.h'
template = 'tabbed'
subtemplate = 'default'
rewrite = false
start = '/* Start flavours */'
end = '/* End flavours */'
hook = ''
light = true

[[item]]
file = '~/.local/share/repos/startpage/style.css'
template = 'startpage'
subtemplate = 'default'
rewrite = false
start = '/* Start flavours */'
end = '/* End flavours */'
hook = ''
light = true
